### ISSUE TITLE
could not create cudnn handle 

### ISSUE THREAD

**Issue by jeremy-rutman** [balancap/SSD-Tensorflow#239]
when i try 

```
python3 eval_ssd_network.py     --eval_dir=${EVAL_DIR}     --data│                                                                                                         
set_dir=${DATASET_DIR}     --dataset_name=pascalvoc_2007     --dataset_split_name=train     --model_name=│                                                                                                         
ssd_300_vgg     --checkpoint_path=${CHECKPOINT_PATH}     --batch_size=1

```
I hit 
```

INFO:tensorflow:Restoring parameters from ./checkpoints/VGG_VOC0712_SSD_300x300_ft_iter_120000.ckpt      │                                                                                                         
2018-05-03 15:30:28.198545: E tensorflow/stream_executor/cuda/cuda_dnn.cc:385] could not create cudnn han│                                                                                                         
dle: CUDNN_STATUS_NOT_INITIALIZED                                                                        │                                                                                                         
2018-05-03 15:30:28.198687: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:369] driver version fil│                                                                                                         
e contents: """NVRM version: NVIDIA UNIX x86_64 Kernel Module  384.90  Tue Sep 19 19:17:35 PDT 2017      │                                                                                                         
GCC version:  gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.5)                                 │                                                                                                         
"""                                                                                                      │                                                                                                         
2018-05-03 15:30:28.198734: E tensorflow/stream_executor/cuda/cuda_dnn.cc:393] possibly insufficient driv│                                                                                                         
er version: 384.90.0                                                                                     │                                                                                                         
2018-05-03 15:30:28.198759: F tensorflow/core/kernels/conv_ops.cc:717] Check failed: stream->parent()->Ge│                                                                                                         
tConvolveAlgorithms( conv_parameters.ShouldIncludeWinogradNonfusedAlgo<T>(), &algorithms)                │                                                                                                         
Aborted (core dumped)                                                   
```

does anyone have an idea?

**Comment by Bovey0809** [comment]
I came across the same problem. It seems to be correlated with tensor flow's version. After tried a lot from stack overflow , I decide to make a virtual environment with cuda8 and tensorflow 1.3, and it works.

**Comment by ciwei123** [comment]
@jeremy-rutman Hi,I meet the same problem,and I restart my computer ,it's works.
